## 2021-07-15
1. async
### async
参考资料：[async](https://github.com/mqyqingfeng/Blog/issues/100)
```
== 0 ==
async function test0() {
    await setTimeout(() =>console.log(111), 3000)
    console.log(222)
}// 222 111
// 问题提出:为啥await没有起作用？await不是返回一个promise，当promise决议后才下一步吗？

== 1 ==
async function test1() {
    await new Promise(resolve => setTimeout(()=>console.log(111), 1000))
    // 如果没有resolve 就不会往下执行 
    console.log(222)// 未执行
}// 111

== 2 ==
async function test2() {
    await new Promise(resolve => setTimeout(()=>resolve(console.log(111)), 1000))
    console.log(222)
}// 111 222 正常版本

== 3 ==
async function test3() {
    await Promise.resolve(setTimeout(()=>console.log(111),500));
    console.log(222)
}// 222 111 因为 await后面是一个已经resolve的promise 所以直接下一步

== 4 ==
async function test4() {
    await Promise.all([setTimeout(()=>console.log(111),500)]);
    console.log(222)
}// 222 111  当all的数组元素不是promise的时候 会调用Promise.resolve方法包装 产生与3一样结果

== 5 ==
async function test5(){
    await new _Promise(resolve=>setTimeout(()=>resolve(console.log(111)),1000));
    console.log(222)
}// 111 222 _Promise是自己模拟的promise

```

由上，
1、await后跟的函数调用立即被调用
```
async function test6() {
    await setTimeout(()=>console.log(1),1000);
    await setTimeout(()=>console.log(2),500);
    await console.log(3)
}// 3 2 1
```
当 await后面跟的不是promise是普通函数的话，后面的普通函数实际上看成由Promise.resolve包裹后执行
```
test7_1()
async function test7_1() {
    console.log(1)
    await Promise.resolve(console.log(2));
    console.log(3)
}
console.log(4)
// 1 2 4 3
```
```
function test7_2() {
    console.log(1)
    Promise.resolve(console.log(2)).then(()=>{console.log(3)})
}
test7_2();
```
产生阻塞的情况是：await后面是未被决议的promise对象才会产生阻塞

阻塞情况的代码
```
test8();
async function test8() {
    await new Promise(resolve => {
        console.log(1);
        setTimeout(() => {
            // resolve();
        }, 100);
    });
    // 由于上一个promise未决议，下面的代码不会执行
    await new Promise(resolve => {
        console.log(2);
        setTimeout(() => {
            resolve();
        }, 100);
    });
    await console.log(3);
    console.log(5); // 5 也不会执行哦
}
// 但并不影响函数外的执行
console.log(6);

输出：1、6
```